# Streamlit Secrets Configuration
# This file contains sensitive credentials and should never be committed to git

# Google Sheets Configuration
sheets_creds_path = "C:/Users/potre/OneDrive/LinkedIn_Automation/google_sheets_credentials.json"
sheet_url = "https://docs.google.com/spreadsheets/d/173Zb-CkHxamDlQ3q7aFD-1Ay3nk6W7hrEq2aD6y4VJ4/edit?usp=sharing"

# Application Settings
cache_ttl = 300  # 5 minutes
default_date_range = 30  # days

# UI Configuration
page_title = "LinkedIn Job Tracker"
page_icon = "📊"
